apiVersion: v1
kind: Namespace
metadata:
  name: guestbook
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  annotations:
      dummy: "test"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
