apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: kubeflow
  annotations:
      dummy: "test"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
