apiVersion: v1
kind: Service
metadata:
  name: mlanywhere-svc
  labels:
    app: mlanywhere-svc
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30003
    protocol: TCP
  selector:
    app: mlanywhere

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mlanywhere
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mlanywhere
    spec:
      containers:
      - name: mlanywhere
        image: mlanywhere:mlanywhere-beta-v1-app

        imagePullPolicy: "IfNotPresent"
        
        # Uncomment if using a proxy
        #env:
        #- name: https_proxy
        #  value: "http://proxy.mycompany.com:80"
        #- name: http_proxy
        #  value: "http://proxy.mycompany.com:80"
        #- name: no_proxy
        #  value: "localhost,127.0.0.1,10.96.0.1"

        ports:
          - containerPort: 5000
