apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  labels:
    app: bolts-classifier
    purpose: mla-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
